name: CI/CD

on:
  workflow_dispatch:
  # push:
  #   branches: [main]

jobs:
  deploy:
    uses: ./.github/workflows/main.yml
    with:
      AzureDefaultRegion: East US
      ProjectName: aks-deploy
      AksClusterName: aks-cluster1
      AZURE_RESOURCE_GROUP: AZURE_RESOURCE_GROUP1
    secrets:
      AzureClientId: ${{ secrets.AzureClientId }}
      AzureClientSecret: ${{ secrets.AzureClientSecret }}
      AzureTenantId: ${{ secrets.AzureTenantId }}
      ACR_Username: ${{ secrets.ACR_Username }}
      ACR_Password: ${{ secrets.ACR_Password }}
      

      
