name: CI/CD

on:
  workflow_dispatch:
  # push:
  #   branches: [main]

jobs:
  deploy:
    uses: ./.github/workflows/main.yml
    with:
      AWSDefaultRegion: us-east-1
      ProjectName: eks-deploy
      EksClusterName: eks-cluster
    secrets:
      AwsAcarinOIDCRole: ${{ secrets.AWS_OIDC_ROLE_NONPROD }}
